apiVersion: batch/v1
kind: Job
metadata:
  name: linerunner-scenario2
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      volumes:
      - name: output-storage
        persistentVolumeClaim:
          claimName: output-claim
      containers:
      - name: linerunner-scenraio2
        image: blackjd/algodevapp-two:1.0.2
        volumeMounts:
          - name: output-storage
            mountPath: /usr/output
      restartPolicy: Never
  backoffLimit: 2